"""Initial schema with tree_node table

Revision ID: 1dde04ee4797
Revises:
Create Date: 2025-08-09 22:06:50.517422

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dde04ee4797"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tree_node",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_key", sa.String(), nullable=False),
        sa.Column("root_id", sa.BigInteger(), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["tree_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tree_node_parent_id"), "tree_node", ["parent_id"], unique=False)
    op.create_index(op.f("ix_tree_node_rank"), "tree_node", ["rank"], unique=False)
    op.create_index(op.f("ix_tree_node_root_id"), "tree_node", ["root_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tree_node_root_id"), table_name="tree_node")
    op.drop_index(op.f("ix_tree_node_rank"), table_name="tree_node")
    op.drop_index(op.f("ix_tree_node_parent_id"), table_name="tree_node")
    op.drop_table("tree_node")
    # ### end Alembic commands ###
